name: Update Manifest

permissions: write-all

on:
  repository_dispatch:
    types: [update-manifest]

jobs:
  update_manifest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Binaries Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: tecolicom/actions-use-apt-tools@v1
        with:
          tools: libtool curl git autotools-dev pkg-config python3 python3-dev python3-pip python3-setuptools python3-wheel python3-gi python3-gi-cairo python3-yaml yamllint
          cache: false

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"
          
      - name: Install Python dependencies
        run: |
          pip install --upgrade pip
          pip install pyyaml yamllint

      - name: Update manifest.yaml
        id: update_manifest
        run: |
          set -e
          python3 scripts/update_manifest.py \
            "./" \
            '${{ toJson(github.event.client_payload) }}'
          yamllint -d relaxed manifest.yaml
          git add .
          echo "manifest_updated=true" >> $GITHUB_OUTPUT

      - name: Commit and Push Updated Manifest
        if: steps.update_manifest.outputs.manifest_updated == 'true'
        uses: EndBug/add-and-commit@v9
        with:
          author_name: "${{ env.author_name }}"
          author_email: "${{ env.author_email }}"
          default_author: user_info
          message: "Update manifest.yaml with new packages [automated]"
          push: true
          pull: "--rebase --autostash"
